site_key: 6LdlTSUTAAAAAMd779T54B9sh7ba1WfAdOkjJ2jW
secret_key: 6LdlTSUTAAAAALkAdc3TLAPR6c7aV7AMIxgnVkn0
widget:
  theme: light
  type: image
  size: ''
  tabindex: 0
  noscript: false
_core:
  default_config_hash: ZKQ03ePk4sH2zESRw4tdZYw__nG2YN4Ru5roPL23g3A
